#!/bin/bash
#COBALT -n 1 -t 60 -q default -O LOG.make.final -M hvincenti@lbl.gov -A PICSSAR 


if [ -z $COBALT_PARTNAME  ] ; then
  echo "Not in job, submitting self"
  exec qsub $0 "$@"
fi

make test 2>&1 $1
make install 
status=$?

echo
echo "do-make: make completed with status: $status"
echo

exit $status


